### ISSUE TITLE
Stop storing URLs

### ISSUE THREAD

**Issue by DavHau** [DavHau/pypi-crawlers#2]
URLs can be computed. They don't need to be stored. Or at least not fully.
Currently the URL crawler saves the URls in the dataset and therefore blows up the download size of [nix-pypi-fetcher](https://github.com/DavHau/nix-pypi-fetcher).
Example for a URL:
`https://files.pythonhosted.org/packages/04/ab/e2eb3e3f90b9363040a3d885ccc5c79fe20c5b8a3caa8fe3bf47ff653260/scipy-1.4.1.tar.gz`

The following URL is equivalent:
https://pypi.org/packages/source/s/scipy/scipy-1.4.1.tar.gz

The logic for computing URLs for sdist releases (like the one above) seems to be:
https://pypi.io/packages/source/{ name[0] }/{ name }/{ name }-{ version }.{ tar.gz | .tgz | .tar.bz2 | zip }

We can probably not compute the file ending and therefore need to store it.
Also I'm not sure if the format of the whole filename is enforced at all by pypi or not. If we don't find a specification for this, we better just store the whole filename.

The logic for computing wheel URLs seems to be:
https://pypi.org/packages/{ python_version }/{ name[0] }/{ name }/{ fn }

Example for a wheel URL:
pypi.org/packages/cp37/s/scipy/scipy-1.4.1-cp37-cp37m-manylinux1_x86_64.whl

Also here the filename seems to be non trivial. We might be able to compute it but only with help of additional metadata which we would need to store. Therefore we might just store the filename itself.
[PEP-427](https://www.python.org/dev/peps/pep-0427/#file-name-convention) specifies the filename format, but I'm not sure if it is enforced.

Synchronously, the nix expression of pypi-fetcher itself must be modified to be able to generate the same URL's: https://github.com/DavHau/nix-pypi-fetcher/issues/2

**Comment by RaitoBezarius** [comment]
> The logic for computing wheel URLs seems to be:
https://pypi.org/packages/{ python_version }/{ name[0] }/{ name }/{ fn }

FWIW, I spent much time on #pypa@freenode and #pypa-dev@freenode
And this won't work, mostly due to the fact Python versions are arbitrary and set by uploader, giving us this superb result: https://gist.github.com/di/93019b51582899c294cfd76ee2d0a4a3

The only way to get the URL in the wheel case is to hit the PyPI Simple API, e.g. "https://pypi.org/pypi/${package-nice-name}/json" and we can filter out based on the name.

**Comment by RaitoBezarius** [comment]
I'm all for a compact way to compute the URLs or store them, but for wheels, it's a difficult problem.

**Comment by DavHau** [comment]
Thanks for figuring that out! Good to know that the python_version for wheels is arbitrary.
Since the python_version is part of the filename, i assume that the [naming convention](https://www.python.org/dev/peps/pep-0427/#file-format) for filenames is also not enforced at all. (it would be difficult to parse it, since the python version can be anything)

Therefore, the minimum we need to store about a wheel release to still be able to generate the URl is: 
`canonicalized name` + `version` + `python_version` + `filename` + `sha256`.
Or am I missing something?
That's already much more compact than what's currently used. (see [latest dump](https://raw.githubusercontent.com/DavHau/nix-pypi-fetcher/6cd2396d6ba500beb16178afc62c4edb5ee81aac/pypi/00.json))
Don't forget, the new format will be highly compressible compared to the random data inside the current URLs.

The new format for sdist could be:
`canonicalized name` + `version` + `filename` + `sha256`

**Comment by RaitoBezarius** [comment]
Indeed, if we have the `python_version`, it's enough; note that we can guess the "perfect" URLs if we know… the blake2_256 hash of the wheel, I spent a lot of time reading the warehouse code: https://github.com/pypa/warehouse/blob/master/warehouse/forklift/legacy.py#L1340 (here it is).

blake2_256 hash has to be computed on our side, it's not exposed, PyPA developers mention that it's impl detail and should not be relied on.

**Comment by DavHau** [comment]
Cool to finally know how to compute these damn URLs ;) But since we don't really need it and storing another hash is expensive, i would instead just use the simpler URL.
All the required information is there now, so we can go ahead and start implementing that new json format and also wheel support for the crawlers. I might start with that tomorrow. In case you are still interested in helping there it might be the best to sync us on matrix.
